# Generated by Django 2.0.3 on 2018-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=191, verbose_name='correo electrónico')),
                ('organization', models.CharField(max_length=100, verbose_name='empresa')),
                ('problem', models.TextField(verbose_name='problema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'correo electrónico',
                'verbose_name_plural': 'correos electrónicos',
            },
        ),
    ]
