# Generated by Django 2.0.3 on 2018-03-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpRequest',
        ),
    ]
