# Generated by Django 2.0.3 on 2018-03-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycle', '0002_auto_20180317_1029'),
        ('website', '0002_delete_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Interaction')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=191, verbose_name='correo electrónico')),
                ('organization', models.CharField(max_length=100, verbose_name='empresa')),
                ('problem', models.TextField(verbose_name='problema')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
                'ordering': ['-created_at'],
            },
            bases=('lifecycle.interaction',),
        ),
    ]
