# Generated by Django 2.0.3 on 2018-03-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('website', '0003_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAccountSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, verbose_name='sesión')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.Account')),
            ],
        ),
    ]
